apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:testdb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: ""
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: ""